services:
  - type: web
    name: tswheels-backend
    env: node
    rootDir: backend
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20.19.0"
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://tanmay:tanmay@cluster0.f1fusyw.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: EASEBUZZ_KEY
        value: 2JRJU40RU
      - key: EASEBUZZ_SALT
        value: 3UW7CPPBT
      - key: RESEND_API_KEY
        value: re_hnWedhMu_Dw6KTiw8qiXXmKQN7FByugvq
