services:
  - type: web
    name: tswheels-backend
    env: node
    rootDir: backend
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - fromGroup: evg-d8vpdqrsq97s738l16tg
      - key: NODE_VERSION
        value: "20.19.0"
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://ckiqrybmvkogklxjtvun.supabase.co
      - key: SUPABASE_JWKS_URL
        value: https://ckiqrybmvkogklxjtvun.supabase.co/auth/v1/.well-known/jwks.json
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: EASEBUZZ_KEY
        value: 2JRJU40RU
      - key: EASEBUZZ_SALT
        value: 3UW7CPPBT
